kind: Deployment
apiVersion: apps/v1
metadata:
  name: pingpong-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: pingpong-service-rolling-updates
          image: gcr.io/pingpong-site1-gcp-demo/pingpong-service-rolling-updates:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 2.0
              memory: 500Mi
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 2
            timeoutSeconds: 1
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 2
            timeoutSeconds: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          env:
            - name: JAVA_OPTS
              value: "-Dspring.profiles.active=whatever"