kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: pingpong

commonLabels:
  component: pingpong

resources:
- namespace.yaml
- deployment.yaml

secretGenerator:
- envs:
  - pingpong-secrets.env.managed
  name: pingpong-secrets