kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: pingpong

commonLabels:
  component: pingpong

resources:
- namespace.yaml
- tls-certificate-secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml