kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  component: pingpong

resources:
- deployment.yaml
- service.yaml

secretGenerator:
- files:
  - pingpong-cloud-storage-sa-key.json=pingpong-cloud-storage-sa-key.json
  name: pingpong-cloud-storage-sa-key