steps:
- id: 'Access secret'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
  - '-c'
  - |
    gcloud secrets versions access 1 --secret=pingpong-secrets-secret > pingpong-secrets.env.managed
- id: 'Perform deploy'
  name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: bash
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials --zone "$$CLOUDSDK_COMPUTE_ZONE" "$$CLOUDSDK_CONTAINER_CLUSTER"
    kubectl kustomize . | kubectl apply -f -
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=pingpong-site1-cluster'