kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: pingpong

commonLabels:
  component: pingpong

resources:
- namespace.yaml
- deployment.yaml

secretGenerator:
- name: pingpong-secrets
  env: pingpong-secrets.env.decrypted
  type: Opaque